[general]
current_preset = 0
path = ""
global_args = ""

[presets]
best = "-f bv*[ext=mp4]+ba[ext=m4a]/b[ext=mp4]/bv*+ba/b"
mp4 = "-f bv*[vcodec^=avc]+ba[ext=m4a]/b"
mp3 = "--extract-audio --audio-format mp3 --audio-quality 0"
